### ISSUE TITLE
!!! [功能] 使用者可以透過頁面，進行新聞資料評論，與其他人交流

### ISSUE THREAD

**Issue by webber0928** [exma-square/Xgag#14]
提高此功能層級，
每個頁面需要有 comment 的功能，可以顯示在畫面上

**Comment by clonn** [comment]
![image](https://cloud.githubusercontent.com/assets/347807/22462531/a0ebba00-e7e8-11e6-99c9-a2dbed849aad.png)


在此頁面底下，可以顯示 comment 功能，以及讓人無限留言

**Comment by zzpengg** [comment]
我看了一下，留言功能已經寫好了，並且會跳到postdetail的頁面，
所以現在的工作是要在首頁的下面也能夠顯示跟留言嗎??

**Comment by clonn** [comment]
首頁下面可顯示留言數量

如果可以的話 detail 的留言可以改成

使用者按 like, 背景框使用者留言顯示藍色
使用者按 dislike, 背景框使用者留言顯示紅色
@zzpengg
