### ISSUE TITLE
範例參考

### ISSUE THREAD

**Issue by wayne1025** [exma-square/Xgag#7]
目前找到的網頁template有

大陸http://danhuaer.com/ 蛋花兒word-press

範例網站
http://ultimate.best9gagclonescript.com/
http://www.gagclonescript.com/
http://demo.gagclonescript.com/
http://themeforest.net/item/fast-forward-faster-than-light-content-sharing/full_screen_preview/7683390

http://codecanyon.net/item/gag-theme-for-media-hunt/full_screen_preview/9301323

https://github.com/MitjaKastelic/Bootstrap9GAGCopy  github bootstrap

**Comment by webber0928** [comment]
感謝 @wayne1025
